### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by yihang-xdu** [silicx/ObjectConceptLearning#1]
Thanks for your great work!  Can you tell me how long does this project need to run?

**Comment by silicx** [comment]
Hi! The three-stage training takes ~13h with 4 TITAN Xp GPUs.

**Comment by yihang-xdu** [comment]
Dear Authors,

Thanks for your reply! However, when I try to download images from the web, I've noticed that some images in the 'resources/url_to_filename.json' file have expired. Could you please provide the downloaded dataset ?

**Comment by silicx** [comment]
Hi, these images have been packed and available [here](https://drive.google.com/drive/folders/1MDBiw45vN4qvjOA8ZuGmJmFhjMVoSBnF?usp=share_link) (see Readme-Datasets). We have recently verified the remaining urls, though some images should be accessible via proper **network proxy**. Feel free to send us the failed urls if you still meet some network problems.

**Comment by yihang-xdu** [comment]
Dear Authors,

Thanks for your reply! I still can't solve the download problem with some images. I have sent the failed urls to your email silicxuyue@sjtu.edu.cn. Thanks a lot!

**Comment by silicx** [comment]
I have sent these images and please check your inbox.

**Comment by yihang-xdu** [comment]
Dear Authors,

Thanks for your help! I have received these pictures and checked them. Thanks again!

**Comment by yihang-xdu** [comment]
Dear Authors,

I'm so sorry to bother you again. I found some problems with the downloaded pictures, so I sent an email to your mailbox, hoping to get your help. Thanks a lot!
