### ISSUE TITLE
checkpoint choose

### ISSUE THREAD

**Issue by yihang-xdu** [silicx/ObjectConceptLearning#2]
Dear Authors,

Thanks for your reply! I have ignored the images whose contents are empty. However, I am uncertain about how to choose the appropriate checkpoint after completing phase 1 training. Could you please guide me on selecting between affordance mAP value and attribute mAP value? Additionally, can you explain the purpose of each of the three stages of training?

The following is the result chart after I completed the first stage of training. Can you tell me how to select checkpoint? Thanks a lot!

![屏幕截图 2024-01-15 095832](https://github.com/silicx/ObjectConceptLearning/assets/103943036/3bf16418-beec-4510-b83d-ec3ba35ca861)

**Comment by yihang-xdu** [comment]
Should I choose the checkpoint_ep60.pt?

![image](https://github.com/silicx/ObjectConceptLearning/assets/103943036/a0e865f6-7c1d-46d1-91ad-7ddc78137665)

**Comment by silicx** [comment]
Hi, I am sorry that there are some errors in the config file for stage 1 training, which i've corrected in the recent commit (stage 2 and 3 are fine). In the training of OCRN, the first stage is to train the attribute sub-network, the second stage is to train the affordance sub-network, and the third stage finetunes the whole model. So you could choose the best epoch according to the attribute mAP in the stage 1, but consider both attribute and affordance mAP in the stage 2 and 3 (the harmonic mean of the two metrics could be a good criterion).

**Comment by yihang-xdu** [comment]
Dear Authors,

I've got the results of three stages of training and done tests. The att value of stage 1 has reached the basic agreement with that of the paper, but the aff result of stage 2 is only 49.28. The final test results are : att=31.15, aff=51.54, S_ITE=18.83, S_ab_ITE=15.08. There are some gaps between the last three values and the results in the paper. I am not sure if this is within the normal range of variation, or can you give me some suggestions to improve, especially the results of stage two?

 I feel that the parameters of stage 2 are very different from those of stage 1 during the training period. Stage 2 requires 6.5 hours of training on 4 A6000 GPUs, and the video memory occupation reaches nearly 40G, while stage 1 requires 1.5 hours and the video memory occupation is only about 10G. So I would like to ask whether it is necessary to change the parameters of stage two?

The results of stage training are as follows：

![R$J4AD5L73RHMYM)7JGLP0M](https://github.com/silicx/ObjectConceptLearning/assets/103943036/7980356f-b164-4f2f-8f84-28cd8b4a4021)

**Comment by DirtyHarryLYL** [comment]
Caused by a dataloader issue, solved via personal contact. Closed.
