### ISSUE TITLE
f_oi

### ISSUE THREAD

**Issue by wuzhaodongaipython** [silicx/ObjectConceptLearning#3]

**Comment by wuzhaodongaipython** [comment]
您好！恭喜您的论文被iccv接收。
您的论文会对我的研究有非常重要的意义。
然而，我有一个细节不太理解，想请教您一下。
在您的论文中，figure5提到f_oi的平均将作为一种输入，但按照我的理解，在测试集中，对于一张图片，我们事先并不知道他的目标属于哪个类，那么这个特定类的平均是如何得到的呢，可能我对论文的解读存在偏差，期待您的回复！！！

**Comment by silicx** [comment]
你好！f_O_i是在训练集上对每种类别的所有样本feature求平均得到，作为物体类别O_i的表征。在测试中，我们对**每个**类别O_i都需要计算f_α_i和f_ß_i，并按照公式7和8进行加权求和，所以不需要知道测试样本的物体类别。

f_O_i is obtained by averaging the features of all samples for each category on the training set, serving as a representation of the object category O_i. During testing, for **each** category O_i, we need to calculate both f_α_i and f_ß_i, and then perform a weighted sum according to Eq. 7 and 8, so there is no need to know the specific object categories of the test sample.

**Comment by wuzhaodongaipython** [comment]
非常感谢您的答复！
再次祝贺中稿iccv
